USE SALESMANAGER;

# CREATE PERMISSION DIAMOND_PRODUCT_CONTROLLER
INSERT INTO `SALESMANAGER`.`PERMISSION`
(`PERMISSION_ID`,
`PRODUCT_AUDIT`,
`DATE_CREATED`,
`DATE_MODIFIED`,
`UPDT_ID`,
`PERMISSION_NAME`)
VALUES
(11,
-1,
NOW(),
NOW(),
NULL,
'DIAMOND_PRODUCT_CONTROLLER');

# CREATE GROUP ADMIN_DIAMOND_PRODUCT
INSERT INTO `SALESMANAGER`.`SM_GROUP`
(`GROUP_ID`,
`PRODUCT_AUDIT`,
`DATE_CREATED`,
`DATE_MODIFIED`,
`UPDT_ID`,
`GROUP_NAME`,
`GROUP_TYPE`)
VALUES
(7,
-1,
NOW(),
NOW(),
NULL,
'ADMIN_DIAMOND_PRODUCT',
'ADMIN');


# LET GROUP 'ADMIN_DIAMOND_PRODUCT' HAS ONLY ONE PERMISSION 'DIAMOND_PRODUCT_CONTROLLER'
INSERT INTO `SALESMANAGER`.`PERMISSION_GROUP`
(`PERMISSION_ID`,
`GROUP_ID`)
VALUES
(11,1);
INSERT INTO `SALESMANAGER`.`PERMISSION_GROUP`
(`PERMISSION_ID`,
`GROUP_ID`)
VALUES
(11,2);
INSERT INTO `SALESMANAGER`.`PERMISSION_GROUP`
(`PERMISSION_ID`,
`GROUP_ID`)
VALUES
(11,
7);

# LET ANY USER WHO HAS 'ADMIN_CATALOGUE' OR 'ADMIN_STORE' HAS THE 'ADMIN_DIAMOND_PRODUCT' BY DEFAULT
INSERT INTO USER_GROUP (USER_ID, GROUP_ID) SELECT DISTINCT USER_ID, 7 FROM USER_GROUP U, SM_GROUP S WHERE U.GROUP_ID=S.GROUP_ID AND (S.GROUP_NAME = 'ADMIN_CATALOGUE' OR S.GROUP_NAME ='ADMIN_STORE');

# ADD NEW COLUMN FOR DIAMOND-PRODUCT
ALTER TABLE PRODUCT ADD COLUMN PRODUCT_DIAMOND TINYINT(1) DEFAULT 0;

# CREATE TABLE "MERCHANT RANK"
CREATE TABLE `MERCHANT_RANK` (
  `RANK_ID` INT(11) NOT NULL,
  `PRODUCT_AUDIT` INT(11) DEFAULT NULL,
  `DATE_CREATED` DATETIME DEFAULT NULL,
  `DATE_MODIFIED` DATETIME DEFAULT NULL,
  `UPDT_ID` VARCHAR(20) DEFAULT NULL,
  `NUM_DIAMOND_PRODUCT` INT(11) NOT NULL,
  `RANK_NAME` VARCHAR(255) NOT NULL,
  `RANK_NAME_ZH` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`RANK_ID`),
  UNIQUE KEY `RANK_ID` (`RANK_ID`),
  UNIQUE KEY `RANK_NAME` (`RANK_NAME`),
  UNIQUE KEY `RANK_NAME_ZH_UNIQUE` (`RANK_NAME_ZH`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

# INIT MERCHANT RANK DATA
LOCK TABLES `MERCHANT_RANK` WRITE;
/*!40000 ALTER TABLE `MERCHANT_RANK` DISABLE KEYS */;
INSERT INTO `MERCHANT_RANK` 
    (`RANK_ID`,`PRODUCT_AUDIT`,`DATE_CREATED`,`DATE_MODIFIED`,`UPDT_ID`,`NUM_DIAMOND_PRODUCT`,`RANK_NAME`,`RANK_NAME_ZH`)
    VALUES 
	(1,-1,'2016-10-31 21:12:53','2016-10-31 21:12:53',NULL,5,'JUNIOR','基本'),
	(2,-1,'2016-10-31 21:12:53','2016-10-31 21:12:53',NULL,10,'MIDDLE','普通'),
	(3,-1,'2016-10-31 21:12:53','2016-10-31 21:12:53',NULL,20,'SENIOR','高级'),
	(4,-1,'2016-10-31 21:12:53','2016-10-31 21:12:53',NULL,100,'VIP','贵宾');
/*!40000 ALTER TABLE `MERCHANT_RANK` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;


# CREATE TABLE "MERCHANT RANK PROFILE"
CREATE TABLE `MERCHANT_RANK_PROFILE` (
  `MCHTRANKPROFILE_ID` BIGINT(20) NOT NULL,
  `PRODUCT_AUDIT` INT(11) DEFAULT NULL,
  `DATE_CREATED` DATETIME DEFAULT NULL,
  `DATE_MODIFIED` DATETIME DEFAULT NULL,
  `UPDT_ID` VARCHAR(20) DEFAULT NULL,
  `NUM_DIAMOND_PRODUCT` INT(11) DEFAULT NULL,
  `RANK_ID` INT(11) DEFAULT NULL,
  PRIMARY KEY (`MCHTRANKPROFILE_ID`),
  UNIQUE KEY `MCHTRANKPROFILE_ID` (`MCHTRANKPROFILE_ID`),
  CONSTRAINT `FK_MERCHANT_PROFILE_RANK` FOREIGN KEY (`RANK_ID`) REFERENCES `MERCHANT_RANK` (`RANK_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;